version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    env_file:
      - .env
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}

    container_name: avalesdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
